version: '3.9'

services:
  postgres-local:
    image: postgres:alpine
    container_name: postgres-local
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d

