server:
  port: 8888
spring:
  application:
    name: estate-management-config-server-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/delloit/env-source.git
          search-paths: estate-management
          username: vrapalis
          password: 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

# Local Profile
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:config/local/application-local.yml
