version: '3.9'
services:
  vrapalis-website-backend:
    image: strapi/strapi
    container_name: vrapalis-website-backend
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: vrapalis_website_db
      DATABASE_HOST: vrapalis-db.ddns.net
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vrapalis
      DATABASE_PASSWORD: vrapalis123456
    volumes:
      - ../strapi:/srv/app
    ports:
      - '1337:1337'
