com.vrapalis.www.security.properties.user.signup.confirm.email.host=http://localhost:4200
com.vrapalis.www.security.properties.user.signup.confirm.email.path=/sign-up/confirm?id=
com.vrapalis.www.security.properties.user.signup.confirm.email.subject=Welcome to entryou
com.vrapalis.www.security.properties.user.signup.confirm.email.text=Welcome to entryou, admit your email address please.
com.vrapalis.www.security.properties.user.signup.confirm.email.linkText=Admit Email Address
