com.vrapalis.www.security.properties.user.signup.confirm.email.host=http://localhost:8080
com.vrapalis.www.security.properties.user.signup.confirm.email.path=/api/users/sign-up?id=
com.vrapalis.www.security.properties.user.signup.confirm.email.subject=Welcome to entryou
com.vrapalis.www.security.properties.user.signup.confirm.email.text=Welcome to entryou, admit your email address please.
com.vrapalis.www.security.properties.user.signup.confirm.email.linkText=Admit Email Address
