spring:
  application:
    name: estate-management-authorization-service
  banner:
    location: classpath:/banner/banner.txt
  task:
    scheduling:
      pool:
        size: 10
server:
  port: 8081


# Local Profile
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:config/local/application-local.yml
