spring:
  application:
    name: user-service

  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: refresh


management:
  endpoints:
    web:
      exposure:
        include: "*"
