version: "3.8"

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/realm-keycloak-example.json
    volumes: 
      - ./keycloak/themes:/opt/jboss/keycloak/themes
      - ./keycloak/import/realm-keycloak-example.json:/tmp/realm-keycloak-example.json
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  frontend:
    image: keycloak_frontend_example
    container_name: keycloak_frontend_example
    build:
      context: ../frontend/.
      dockerfile: apps/keycloak-demo/Dockerfile
    ports:
      - 4200:80

  backend:
    image: keycloak_backend_example
    container_name: keycloak_backend_example
    build:
      context: ../backend/app/.
      dockerfile: Dockerfile
    ports:
      - 8081:8081

volumes:
  postgres:
