smart-it-development.entryou.security.jwt.secret=mySecretJwt
smart-it-development.entryou.security.jwt.expire-date=432000000
smart-it-development.entryou.security.jwt.header=Authorization
smart-it-development.entryou.security.jwt.token-prefix=Bearer
smart-it-development.entryou.security.jwt.claim-email=email
smart-it-development.entryou.security.jwt.claim-username=username
smart-it-development.entryou.security.jwt.claim-info=info
smart-it-development.entryou.security.jwt.claim-roles=roles
smart-it-development.entryou.security.jwt.claim-id=id
smart-it-development.entryou.security.jwt.claim-principals=principals