version: '3.6'

services:
  entryou-rabbitmq-dev:
    build:
      context: ./rabbitmq      
    image: entryou_rabbitmq_dev
    container_name: entryou_rabbitmq_dev
    network_mode: host

  entryou-consul-dev:
    image: consul
    network_mode: host
    container_name: entryou_consul_agent_dev
    restart: on-failure

  entryou-uaa-dev:
    image: vrapalis/entryou/entryou-uaa:0.0.1-snapshot
    container_name: entryou_uaa_dev
    network_mode: host
    expose:
      - 8081
    restart: on-failure
    environment:
      - SPRING.PROFILES.ACTIVE=dev-local
      - SPRING.CLOUD.CONSUL.HOST=localhost
      - SPRING.CLOUD.CONSUL.ENABLED=true
      - SPRING.DATASOURCE.URL=jdbc:postgresql://localhost:5432/entryou_uaa_db_dev
      - SPRING.DATASOURCE.USERNAME=admin
      - SPRING.DATASOURCE.PASSWORD=admin
      - SERVER.PORT=8081
    depends_on:
      - entryou-push-dev
      - entryou-consul-dev
      - entryou-uaa-db-dev

  entryou-uaa-db-dev:
    image: postgres
    container_name: entryou_uaa_db_dev
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=entryou_uaa_db_dev
    ports:
      - 5432:5432

  entryou-push-dev:
    image: vrapalis/entryou/entryou-push:0.0.1-snapshot
    container_name: entryou_push_dev
    network_mode: host
    expose:
      - 8082
    restart: on-failure
    environment:
      - SPRING.PROFILES.ACTIVE=dev-local
      - SPRING.CLOUD.CONSUL.HOST=localhost
      - SPRING.CLOUD.CONSUL.ENABLED=true
      - SPRING.DATASOURCE.URL=jdbc:postgresql://localhost:5433/entryou_push_db_dev
      - SPRING.DATASOURCE.USERNAME=admin
      - SPRING.DATASOURCE.PASSWORD=admin
      - SERVER.PORT=8082
      ### Frontend related properties
      - SMART-IT-DEVELOPMENT.ENTRYOU.UAA.EMAIL-HOST=https://frontent-host
      - SMART-IT-DEVELOPMENT.ENTRYOU.UAA.EMAIL-SERVICE-PATH=/confirm?account
      - SMART-IT-DEVELOPMENT.ENTRYOU.UAA.EMAIL-SUBJECT=Entryou confirm email
      - SMART-IT-DEVELOPMENT.ENTRYOU.UAA.EMAIL-TEXT=Confirm your email,
    depends_on:
      - entryou-rabbitmq-dev
      - entryou-consul-dev
      - entryou-push-db-dev

  entryou-push-db-dev:
    image: postgres
    container_name: entryou_push_db_dev
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=entryou_push_db_dev
    ports:
      - 5433:5432

  entryou-entry-dev:
    image: vrapalis/entryou/entryou-entry:0.0.1-snapshot
    container_name: entryou_entry_dev
    network_mode: host
    expose:
      - 8083
    restart: on-failure
    environment:
      - SPRING.PROFILES.ACTIVE=dev-local
      - SPRING.CLOUD.CONSUL.HOST=localhost
      - SPRING.CLOUD.CONSUL.ENABLED=true
      - SPRING.DATASOURCE.URL=jdbc:postgresql://localhost:5434/entryou_entry_db_dev
      - SPRING.DATASOURCE.USERNAME=admin
      - SPRING.DATASOURCE.PASSWORD=admin
      - SERVER.PORT=8083
    depends_on:
      - entryou-push-dev
      - entryou-consul-dev
      - entryou-uaa-db-dev

  entryou-entry-db-dev:
    image: postgres
    container_name: entryou_entry_db_dev
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=entryou_entry_db_dev
    ports:
      - 5434:5432

  entryou-db-adminer-dev:
    image: adminer
    container_name: entryou_db_adminer_dev
    restart: on-failure
    ports:
      - 9090:8080
    depends_on:
      - entryou-uaa-db-dev
      - entryou-push-db-dev
      - entryou-entry-db-dev

  entryou-api-gateway-swagger-ui-dev:
    image: swaggerapi/swagger-ui
    container_name: entryou_api_gateway_swagger_ui_dev
    network_mode: host
    restart: on-failure
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
      - PORT=9091
    volumes:
      - ./swagger:/swagger
