version: '3.6'

services:
  estate-management-consul:
    image: consul
    container_name: estate-management-consul-local
    network_mode: host
    restart: on-failure

  estate-management-db:
    image: postgres:alpine
    container_name: estate-management-db
    restart: on-failure
    networks:
      - estate-management-nt
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

networks:
  estate-management-nt:
    name: estate-management-nt
    driver: bridge