---
openapi: 3.0.1
info:
  title: Delloit API Documentation
  description: This documentation list all apis for delloit estate management application.
  contact:
    name: Vitali Rapalis
    email: vitali.rapalis@gmail.com
  version: 0.0.1
servers:
- url: https://delloit-api.ddns.net
  description: Generated server url
tags:
- name: Authentication
  description: The endpoints provide authentication to api caller.
paths:
  "/sign-up":
    post:
      tags:
      - Authentication
      summary: Sign up endpoint
      description: The endpoint will generated login password for you and send it to your mobile device.
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserSignUpUserDto"
        required: true
      responses:
        '200':
          description: Sign up success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserSignUpSuccessResponseDto"
        '400':
          description: Sign up error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AbstractServerResponseDto"
        '422':
          description: Bean validation exception
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AbstractServerResponseDto"
  "/sign-in":
    post:
      tags:
      - Authentication
      summary: Sign in endpoint
      description: Endpoint will generate the jwt token.
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserSignInDto"
        required: true
      responses:
        '200':
          description: Sign in success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserSignInSuccessResponseDto"
        '400':
          description: Sign in error, ex. provided wrong email or password
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AbstractServerResponseDto"
        '422':
          description: Bean validation error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AbstractServerResponseDto"
components:
  schemas:
    UserSignUpUserDto:
      type: object
      properties:
        mobilePhone:
          pattern: "^(\\+\\d{1,3}( )?)?((\\(\\d{1,3}\\))|\\d{1,3})[- .]?\\d{3,4}[-
            .]?\\d{4}$"
          type: string
    UserSignUpSuccessResponseDto:
      type: object
      properties:
        msg:
          type: string
        detailedMsg:
          type: string
        jwt:
          type: string
    AbstractServerResponseDto:
      type: object
      properties:
        msg:
          type: string
        detailedMsg:
          type: string
    UserSignInDto:
      type: object
      properties:
        mobilePhone:
          pattern: "^(\\+\\d{1,3}( )?)?((\\(\\d{1,3}\\))|\\d{1,3})[- .]?\\d{3,4}[-
            .]?\\d{4}$"
          type: string
        password:
          type: string
    UserSignInSuccessResponseDto:
      type: object
      properties:
        msg:
          type: string
        detailedMsg:
          type: string
        jwt:
          type: string

