spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/entryou_store_db_dev
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false