apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - services
      - endpoints
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch