spring:
  application:
    name: estate-management-push-service
  banner:
    location: classpath:/banner/banner.txt
server:
  port: 8082

# Local Profile
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:config/local/application-local.yml
