spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smart.it.develop@gmail.com
    password: auto246135
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/entryou_push_db_dev
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false

  flyway:
    locations: classpath:db/migration/dev
    enabled: false

smart-it-development:
  swagger:
    contact-name: vrapalis
    contact-url: vrapalis.com
    contact-email: vitali.rapalis@mail.ru
    api-base-packages: com.smartitdevelopment.www
    api-description: Entryou
    api-title: Rest api
    api-version: 0.0.1
  entryou:
    uaa:
      email-host: "http://localhost:8080"
      email-service-path: "/confirm?account"
      email-subject: "Entryou confirm email!!!"
      email-text: "Confirm your email, "

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
