spring:
  application:
    name: entroyu-apps-oauth2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 510777182796-be62clqeh8ik12cuclrmjqhqqc15c44d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            scope:
              - user:email
              - read:user
          microsoft:
            clientId: a10d7d10-bada-4faf-9d90-85c8d8a91c40
            clientSecret: 8XX7Q~yqyW3tnUKoIkImUsvhvYo8FqYKVWkSe
            client-name: Test1
            authorization-grant-type: authorization_code
            redirect-uri: 'https://vrapalis-oauth2.ddns.net/login/oauth2/code/{registrationId}'
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - https://graph.microsoft.com/.default
              - openid
              - profile
        provider:
          microsoft:
           issuer-uri: https://login.microsoftonline.com/815692a5-a5c8-461a-b480-6675c658ad5b/v2.0
           token-uri: https://login.microsoftonline.com/815692a5-a5c8-461a-b480-6675c658ad5b/oauth2/v2.0/token
           authorization-uri: https://login.microsoftonline.com/815692a5-a5c8-461a-b480-6675c658ad5b/oauth2/v2.0/authorize

com:
  vrapalis:
    www:
      oauth2:
        clients:
          classes:
            google:
              - bi-google
              - text-primary
            facebook :
              - bi-facebook
              - text-info
            github :
              - bi-github
              - text-black
            azuread :
              - bi-microsoft
              - text-success
