db-name: oauth2_dev_db

logging:
  level:
    com.vrapalis.www.backend.libs.shared.oauth2.server: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://vrapalis.ddns.net

  mail:
    host: smtp.gmail.com
    port: 587
    username: it.development.for.you@gmail.com
    password: PsD4vaOHn
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
com:
  vrapalis:
    www:
      oauth2:
        email:
          password:
            subject: Reset Password!!!
            text: '<a href=%s>Please click on link to accomplish the reset password process</a>'
            password-path: '/reset-password?code='
            host: https://vrapalis-oauth2.ddns.net
          registration:
            subject: Registration Success!!!
            text: '<a href=%s>Please click on link to accomplish the registration process</a>'
            registration-path: '/registration?code='
            host: https://vrapalis-oauth2.ddns.net
